# namespace:
#   name: sandbox

# service:
#   port: 4111
#   targetPort: 3111
#   protocol: TCP
#   type: ClusterIP

# image:
#   repository: mohamedelsherif/techtrends
#   tag: latest
#   pullPolicy: Always

# replicaCount: 1

# resources:
#   requests:
#     cpu: 250m
#     memory: 64Mi
#   limits:
#     cpu: 500m
#     memory: 128Mi

# containerPort: 3111

# livenessProbe:
#   httpGet:
#     path: /healthz
#     port: 3111
#   initialDelaySeconds: 5
#   periodSeconds: 5

# readinessProbe:
#   httpGet:
#     path: /healthz
#     port: 3111
#   initialDelaySeconds: 5
#   periodSeconds: 5

namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

# resources:
#   requests:
#     memory: 64Mi
#     cpu: 250m
#   limits:
#     memory: 128Mi
#     cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz